name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup database
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing_db
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
        run: |
          php artisan migrate --force

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing_db
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
